# -*- coding: utf-8 -*-
"""FainWatch-Detector_de_lipotimia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myN2r3-ywueJxkUQ23RztdTLNPcB_KHF
"""



# ╔══════════════════════════════════════════════════════════════╗
# ║   DETECTOR DE LIPOTIMIA v8 — AUTOINSTALABLE                  ║
# ║   Pega todo en UNA sola celda y ejecuta.                     ║
# ║   NOVEDADES v8:                                              ║
# ║     · Estrategia 1 — Velocidad: giros rápidos ignorados      ║
# ║     · Estrategia 2 — Coherencia: exige ≥2 parámetros         ║
# ║       distintos activos para subir de nivel                  ║
# ║     · Estrategia 3 — Duración mínima sostenida               ║
# ║       antes de que parámetros posturales puntúen             ║
# ╚══════════════════════════════════════════════════════════════╝

import subprocess, sys, os

# ==============================================================
# PASO 1 — INSTALACIÓN AUTOMÁTICA
# ==============================================================

def instalar(paquete):
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", paquete, "-q"]
    )

for pkg in ["mediapipe", "opencv-python-headless", "Pillow", "reportlab"]:
    try:
        __import__(pkg.replace("-python-headless","").replace("-","_"))
        print(f"✔ {pkg} ya instalado")
    except ImportError:
        print(f"⬇ Instalando {pkg}...")
        instalar(pkg)
        print(f"✔ {pkg} instalado")

# ==============================================================
# PASO 2 — DESCARGA AUTOMÁTICA DE MODELOS
# ==============================================================

MODELOS = {
    "face_landmarker.task": (
        "https://storage.googleapis.com/mediapipe-models/"
        "face_landmarker/face_landmarker/float16/1/face_landmarker.task"
    ),
    "pose_landmarker.task": (
        "https://storage.googleapis.com/mediapipe-models/"
        "pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task"
    ),
}

import urllib.request

for nombre, url in MODELOS.items():
    if os.path.exists(nombre):
        print(f"✔ {nombre} ya existe")
    else:
        print(f"⬇ Descargando {nombre}...")
        urllib.request.urlretrieve(url, nombre)
        print(f"✔ {nombre} descargado ({os.path.getsize(nombre)//1024} KB)")

# ==============================================================
# PASO 3 — IMPORTS
# ==============================================================

import cv2
import mediapipe as mp
import numpy as np
import base64
import io
import time
import csv
import threading
from collections import deque
from dataclasses import dataclass, field
from typing import Optional

from PIL import Image
from IPython.display import display, Javascript
from IPython.display import Image as IPImage
from google.colab.output import eval_js
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# ReportLab para PDF
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, HRFlowable)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT

print("✔ Imports OK")

# ==============================================================
# CONFIG
# ==============================================================

@dataclass
class Config:
    # — parámetros originales —
    umbral_blink:           float = 0.65
    umbral_boca:            float = 0.07
    umbral_roll:            float = 20.0
    umbral_pitch:           float = 25.0
    umbral_caida:           float = 0.10
    # — palidez y malestar (v4/v5) —
    umbral_palidez:         float = 0.25
    umbral_malestar:        float = 0.30
    # — mirada fija (v7) —
    # Ya NO hay umbral EAR fijo. El sistema aprende el EAR normal
    # del donante durante la calibración y detecta cuando sube
    # 'ear_margen_sigma' desviaciones estándar por encima de su baseline.
    ear_margen_sigma:       float = 2.0    # cuántas σ por encima del EAR normal = alerta
    umbral_movimiento_iris: float = 0.008  # movimiento iris normalizado mínimo
    frames_mirada_fija:     int   = 22     # ~1.8s a 12fps — más exigente que v6
    # — bostezo (v7b) — solo historial, no afecta nivel de riesgo
    umbral_mar_bostezo:     float = 0.45   # MAR mínimo para considerar boca muy abierta
    umbral_squint_bostezo:  float = 0.25   # entrecerrado mínimo de ojos (blendshape)
    frames_bostezo:         int   = 14     # ~1.2s a 12fps para confirmar bostezo
    # — v8: filtros de movimiento voluntario —
    # Estrategia 1: velocidad — giros más rápidos que este umbral se ignoran
    umbral_velocidad_giro:  float = 3.5    # grados por frame; por encima = movimiento voluntario
    # Estrategia 2: coherencia — mínimo de parámetros distintos activos para puntuar
    min_params_coherencia:  int   = 2      # al menos 2 señales distintas simultáneas
    # Estrategia 3: duración — frames mínimos sostenidos para que roll/pitch/caída puntúen
    frames_postural_minimo: int   = 8      # ~0.7s a 12fps antes de que la postura cuente
    # — generales —
    calibracion_sigma:      float = 2.5
    alpha_ema:              float = 0.30
    frames_ojos_umbral:     int   = 10
    ventana_riesgo:         int   = 15
    frames_calibracion:     int   = 50
    fps_objetivo:           float = 12.0
    log_path: Optional[str]       = None
    num_faces:              int   = 1
    min_confianza:          float = 0.5

# ==============================================================
# LANDMARKS
# ==============================================================

BOCA_SUP     = 13;  BOCA_INF    = 14;  BOCA_IZQ = 61; BOCA_DER = 291
FRENTE       = 10;  MENTON      = 152; NARIZ_TIP = 1
MEJILLA_IZQ  = 234; MEJILLA_DER = 454
POSE_NARIZ   = 0;   POSE_HOMBRO_IZQ = 11; POSE_HOMBRO_DER = 12

# Landmarks del párpado para EAR
# Ojo izquierdo: superior=159, inferior=145, ext=33, int=133
# Ojo derecho:   superior=386, inferior=374, ext=362, int=263
OJO_IZQ_SUP = 159; OJO_IZQ_INF = 145; OJO_IZQ_EXT = 33;  OJO_IZQ_INT = 133
OJO_DER_SUP = 386; OJO_DER_INF = 374; OJO_DER_EXT = 362; OJO_DER_INT = 263

# Landmarks del centro del iris (MediaPipe Face Mesh 478 puntos)
IRIS_IZQ_CENTRO = 468
IRIS_DER_CENTRO = 473

# Zonas de piel para palidez
ZONAS_PIEL = [
    (FRENTE,       0.50),
    (MEJILLA_IZQ,  0.25),
    (MEJILLA_DER,  0.25),
]

# ==============================================================
# BLENDSHAPES DE MALESTAR
# ==============================================================

BLENDSHAPES_MALESTAR = {
    "browLowererLeft":    0.15,
    "browLowererRight":   0.15,
    "browInnerUp":        0.10,
    "noseSneerLeft":      0.10,
    "noseSneerRight":     0.10,
    "cheekSquintLeft":    0.10,
    "cheekSquintRight":   0.10,
    "mouthFrownLeft":     0.10,
    "mouthFrownRight":    0.10,
    "eyeSquintLeft":      0.05,
    "eyeSquintRight":     0.05,
}
_PESO_TOTAL_MALESTAR = sum(BLENDSHAPES_MALESTAR.values())

# ==============================================================
# EMA FILTER
# ==============================================================

class EMA:
    def __init__(self, alpha=0.3):
        self.alpha = alpha
        self.value = None

    def update(self, x):
        self.value = x if self.value is None else self.alpha * x + (1 - self.alpha) * self.value
        return self.value

    def reset(self):
        self.value = None

# ==============================================================
# BASELINE DE COLOR (v5)
# ==============================================================

class BaselineColor:
    """Aprende el color de piel del donante durante la calibración
    y devuelve un score de palidez relativo a ese baseline."""

    def __init__(self):
        self._buf_V = {idx: [] for idx, _ in ZONAS_PIEL}
        self._buf_S = {idx: [] for idx, _ in ZONAS_PIEL}
        self._buf_G = {idx: [] for idx, _ in ZONAS_PIEL}
        self.ref_V: dict = {}
        self.ref_S: dict = {}
        self.ref_G: dict = {}
        # EAR baseline — NUEVO v7
        self._buf_ear: list = []
        self.ear_media: float = 0.30    # valor por defecto razonable
        self.ear_std:   float = 0.03
        self.listo = False

    def _extraer_stats(self, frame, lm, idx, h, w, tam=22):
        px = int(lm[idx].x * w)
        py = int(lm[idx].y * h)
        x1 = max(0, px - tam // 2)
        y1 = max(0, py - tam // 2)
        roi = frame[y1:min(h, y1+tam), x1:min(w, x1+tam)]
        if roi.size == 0:
            return None
        hsv   = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV).astype(float)
        return hsv[:,:,2].mean(), hsv[:,:,1].mean(), roi[:,:,1].astype(float).mean()

    def acumular(self, frame, lm, ear=None):
        if self.listo:
            return
        h, w = frame.shape[:2]
        for idx, _ in ZONAS_PIEL:
            stats = self._extraer_stats(frame, lm, idx, h, w)
            if stats:
                V, S, G = stats
                self._buf_V[idx].append(V)
                self._buf_S[idx].append(S)
                self._buf_G[idx].append(G)
        # Acumular EAR normal del donante
        if ear is not None and ear > 0.05:   # descartar frames con ojos cerrados
            self._buf_ear.append(ear)

    def fijar(self):
        for idx, _ in ZONAS_PIEL:
            if self._buf_V[idx]:
                self.ref_V[idx] = float(np.mean(self._buf_V[idx]))
                self.ref_S[idx] = float(np.mean(self._buf_S[idx]))
                self.ref_G[idx] = float(np.mean(self._buf_G[idx]))
        # Baseline EAR personal — NUEVO v7
        if self._buf_ear:
            self.ear_media = float(np.mean(self._buf_ear))
            self.ear_std   = float(max(np.std(self._buf_ear), 0.01))  # mínimo 0.01 para evitar σ=0
        self.listo = True
        print("Baseline color piel fijado:")
        for idx, _ in ZONAS_PIEL:
            zona = {FRENTE:"Frente", MEJILLA_IZQ:"Mej.Izq", MEJILLA_DER:"Mej.Der"}.get(idx)
            print(f"   {zona}: V={self.ref_V.get(idx,0):.1f}  "
                  f"S={self.ref_S.get(idx,0):.1f}  "
                  f"G={self.ref_G.get(idx,0):.1f}")
        print(f"Baseline EAR: media={self.ear_media:.3f}  σ={self.ear_std:.3f}  "
              f"→ umbral alerta > {self.ear_media + 2*self.ear_std:.3f}")

    def score_palidez(self, frame, lm):
        if not self.listo:
            return 0.0
        h, w = frame.shape[:2]
        score_total = peso_total = 0.0
        for idx, peso_zona in ZONAS_PIEL:
            if idx not in self.ref_V:
                continue
            stats = self._extraer_stats(frame, lm, idx, h, w)
            if stats is None:
                continue
            V_act, S_act, G_act = stats
            dV = max(0.0,  (V_act - self.ref_V[idx]) / 255.0)
            dS = max(0.0, -(S_act - self.ref_S[idx]) / 255.0)
            dG = max(0.0, -(G_act - self.ref_G[idx]) / 255.0)
            score_zona    = 0.45 * dV + 0.35 * dS + 0.20 * dG
            score_total  += score_zona * peso_zona
            peso_total   += peso_zona
        if peso_total == 0:
            return 0.0
        return float(np.clip(score_total / (peso_total * 0.25), 0.0, 1.0))

# ==============================================================
# DETECTOR DE MIRADA FIJA — NUEVO v6
# ==============================================================

class DetectorMiradaFija:
    """
    Detecta la combinación clínica de alarma vagal:
      1. Ojos MUY abiertos  → EAR supera el baseline personal del donante
                               en más de 'ear_margen_sigma' desviaciones típicas
      2. Iris INMÓVIL        → desplazamiento del centro del iris
                               entre frames < umbral_movimiento_iris

    Al usar el baseline personal se eliminan los falsos positivos
    con donantes que naturalmente tienen los ojos más abiertos.
    """

    def __init__(self, cfg, baseline_color):
        self.cfg            = cfg
        self.baseline_color = baseline_color   # referencia al mismo objeto
        self._iris_prev_izq = None
        self._iris_prev_der = None
        self._frames_activo = 0
        self._ema_ear = EMA(alpha=0.4)
        self._ema_mov = EMA(alpha=0.4)

    def _ear_landmarks(self, lm, sup, inf, ext, int_):
        v = np.sqrt((lm[sup].x - lm[inf].x)**2 + (lm[sup].y - lm[inf].y)**2)
        h = np.sqrt((lm[ext].x - lm[int_].x)**2 + (lm[ext].y - lm[int_].y)**2)
        return v / (h + 1e-6)

    def _movimiento_iris(self, lm):
        ix = lm[IRIS_IZQ_CENTRO].x;  iy = lm[IRIS_IZQ_CENTRO].y
        dx = lm[IRIS_DER_CENTRO].x;  dy = lm[IRIS_DER_CENTRO].y
        if self._iris_prev_izq is None:
            self._iris_prev_izq = (ix, iy)
            self._iris_prev_der = (dx, dy)
            return None
        mov_izq = np.sqrt((ix - self._iris_prev_izq[0])**2 + (iy - self._iris_prev_izq[1])**2)
        mov_der = np.sqrt((dx - self._iris_prev_der[0])**2 + (dy - self._iris_prev_der[1])**2)
        self._iris_prev_izq = (ix, iy)
        self._iris_prev_der = (dx, dy)
        return (mov_izq + mov_der) / 2.0

    def actualizar(self, lm):
        """
        Devuelve (ear, movimiento_iris, alerta_mirada_fija).
        El umbral EAR se calcula dinámicamente desde el baseline del donante.
        """
        cfg = self.cfg

        ear_izq = self._ear_landmarks(lm, OJO_IZQ_SUP, OJO_IZQ_INF, OJO_IZQ_EXT, OJO_IZQ_INT)
        ear_der = self._ear_landmarks(lm, OJO_DER_SUP, OJO_DER_INF, OJO_DER_EXT, OJO_DER_INT)
        ear = self._ema_ear.update((ear_izq + ear_der) / 2.0)

        mov_raw = self._movimiento_iris(lm)
        if mov_raw is None:
            return ear, 0.0, False
        mov = self._ema_mov.update(mov_raw)

        # Umbral EAR dinámico: baseline + N desviaciones típicas — NUEVO v7
        umbral_ear = self.baseline_color.ear_media + cfg.ear_margen_sigma * self.baseline_color.ear_std

        ojos_muy_abiertos = ear > umbral_ear
        iris_inmovil      = mov < cfg.umbral_movimiento_iris

        if ojos_muy_abiertos and iris_inmovil:
            self._frames_activo += 1
        else:
            self._frames_activo = max(0, self._frames_activo - 1)

        alerta = self._frames_activo >= cfg.frames_mirada_fija
        return ear, mov, alerta

    def reset(self):
        self._iris_prev_izq = None
        self._iris_prev_der = None
        self._frames_activo = 0
        self._ema_ear.reset()
        self._ema_mov.reset()

# ==============================================================
# DETECTOR DE BOSTEZO — NUEVO v7b
# ==============================================================

class DetectorBostezo:
    """
    Detecta bostezos combinando dos señales simultáneas:

      1. MAR muy alto (boca muy abierta durante varios segundos)
         El umbral es más exigente que el de 'boca abierta' del
         detector principal, para no confundir con hablar o suspirar.

      2. Ojos entrecerrados al mismo tiempo
         Blendshapes eyeSquintLeft + eyeSquintRight: el cierre
         reflejo de los ojos durante el bostezo es involuntario
         y es lo que lo distingue de abrir la boca por sorpresa
         o malestar.

    El bostezo se registra en el CSV y en el panel de pantalla
    pero NO suma puntos al nivel de riesgo de lipotimia.

    Además lleva un contador acumulado de bostezos en la sesión,
    útil para el historial (varios bostezos seguidos = fatiga).
    """

    def __init__(self, cfg):
        self.cfg             = cfg
        self._frames_activo  = 0
        self._en_bostezo     = False   # True mientras dura el bostezo actual
        self.total_bostezos  = 0       # contador acumulado de la sesión
        self.ultimo_bostezo  = "—"     # hora del último bostezo detectado

    def actualizar(self, lm, fr):
        """
        lm : face_landmarks[0]  o None
        fr : resultado detect_for_video  (para blendshapes)

        Devuelve (mar, squint, bostezo_activo).
          mar          : float — apertura de boca normalizada actual
          squint       : float — media de entrecerrado de ojos
          bostezo_activo : bool — True si hay bostezo en curso
        """
        cfg = self.cfg

        if lm is None or not fr.face_blendshapes:
            self._frames_activo = max(0, self._frames_activo - 1)
            return 0.0, 0.0, False

        # MAR desde landmarks (mismo cálculo que apertura_boca pero sin EMA)
        mar = dist(lm[BOCA_SUP], lm[BOCA_INF]) / (
              dist(lm[BOCA_IZQ], lm[BOCA_DER]) + 1e-6)

        # Entrecerrado de ojos desde blendshapes
        bl = {b.category_name: b.score for b in fr.face_blendshapes[0]}
        squint = (bl.get("eyeSquintLeft", 0.0) + bl.get("eyeSquintRight", 0.0)) / 2.0

        # Ambas condiciones simultáneas
        boca_muy_abierta  = mar    > cfg.umbral_mar_bostezo
        ojos_entrecerrados = squint > cfg.umbral_squint_bostezo

        if boca_muy_abierta and ojos_entrecerrados:
            self._frames_activo += 1
        else:
            self._frames_activo = max(0, self._frames_activo - 1)

        bostezo_confirmado = self._frames_activo >= cfg.frames_bostezo

        # Contar cada bostezo una sola vez (flanco de subida)
        if bostezo_confirmado and not self._en_bostezo:
            self._en_bostezo    = True
            self.total_bostezos += 1
            self.ultimo_bostezo  = time.strftime("%H:%M:%S")
        elif not bostezo_confirmado and self._en_bostezo:
            self._en_bostezo = False

        return mar, squint, bostezo_confirmado

# ==============================================================
# FILTRO DE MOVIMIENTO VOLUNTARIO — NUEVO v8
# ==============================================================

class FiltroMovimientoVoluntario:
    """
    Implementa las tres estrategias para distinguir movimiento
    voluntario (hablar, girar a mirar algo) de síntoma de lipotimia.

    Estrategia 1 — Velocidad:
        Mide el cambio de roll y pitch entre frames consecutivos.
        Un giro voluntario es rápido (ΔAngulo/frame alto).
        Un cabeceo por lipotimia es lento y progresivo.
        Si la velocidad supera umbral_velocidad_giro → se ignora
        ese frame para los parámetros posturales.

    Estrategia 2 — Coherencia:
        Cuando alguien habla, la boca está abierta pero los ojos
        están alertas, la piel tiene color normal y la postura es
        correcta. La lipotimia arrastra varios parámetros a la vez.
        Exige min_params_coherencia parámetros distintos activos
        simultáneamente antes de subir el nivel de riesgo.

    Estrategia 3 — Duración mínima:
        Un giro voluntario dura 1-3 segundos y el donante vuelve.
        Una desviación por lipotimia se mantiene o empeora.
        Los parámetros posturales (roll, pitch, caída) solo puntúan
        si llevan frames_postural_minimo frames consecutivos activos.
    """

    def __init__(self, cfg):
        self.cfg = cfg
        # Estrategia 1: velocidad
        self._roll_prev  = None
        self._pitch_prev = None
        # Estrategia 3: contadores de duración por parámetro postural
        self._frames_roll  = 0
        self._frames_pitch = 0
        self._frames_caida = 0

    def actualizar(self, roll, pitch, caida, cfg):
        """
        Devuelve (roll_ok, pitch_ok, caida_ok, movimiento_rapido).

        roll_ok / pitch_ok / caida_ok: True si el parámetro supera
        su umbral Y pasa los filtros de velocidad y duración.
        movimiento_rapido: True si el frame actual parece voluntario.
        """
        # ── Estrategia 1: velocidad ──────────────────────────────
        movimiento_rapido = False
        if self._roll_prev is not None:
            delta_roll  = abs(roll  - self._roll_prev)
            delta_pitch = abs(pitch - self._pitch_prev)
            if delta_roll > cfg.umbral_velocidad_giro or \
               delta_pitch > cfg.umbral_velocidad_giro:
                movimiento_rapido = True

        self._roll_prev  = roll
        self._pitch_prev = pitch

        # Si el movimiento es rápido, no acumulamos duración
        # y descartamos posturales este frame
        if movimiento_rapido:
            self._frames_roll  = max(0, self._frames_roll  - 1)
            self._frames_pitch = max(0, self._frames_pitch - 1)
            self._frames_caida = max(0, self._frames_caida - 1)
            return False, False, False, True

        # ── Estrategia 3: duración mínima ────────────────────────
        umbral_min = cfg.frames_postural_minimo

        if roll > cfg.umbral_roll:
            self._frames_roll += 1
        else:
            self._frames_roll = max(0, self._frames_roll - 1)

        if pitch > cfg.umbral_pitch:
            self._frames_pitch += 1
        else:
            self._frames_pitch = max(0, self._frames_pitch - 1)

        if caida > cfg.umbral_caida:
            self._frames_caida += 1
        else:
            self._frames_caida = max(0, self._frames_caida - 1)

        roll_ok  = self._frames_roll  >= umbral_min
        pitch_ok = self._frames_pitch >= umbral_min
        caida_ok = self._frames_caida >= umbral_min

        return roll_ok, pitch_ok, caida_ok, False

# ==============================================================
# CALIBRADOR
# ==============================================================

class Calibrador:
    def __init__(self, cfg, baseline_color):
        self.cfg            = cfg
        self.baseline_color = baseline_color
        self.buffer = {k: [] for k in ["blink","boca","roll","pitch","caida","malestar"]}
        self.calibrado = False

    def agregar(self, frame, lm, blink, boca, roll, pitch, caida, malestar, ear=0.0):
        if self.calibrado:
            return
        if lm is not None:
            self.baseline_color.acumular(frame, lm, ear=ear)
        for k, v in zip(self.buffer, [blink, boca, roll, pitch, caida, malestar]):
            self.buffer[k].append(v)
        if len(self.buffer["blink"]) >= self.cfg.frames_calibracion:
            self._calcular()

    def _calcular(self):
        k = self.cfg.calibracion_sigma
        for clave, attr in [
            ("boca",     "umbral_boca"),
            ("roll",     "umbral_roll"),
            ("pitch",    "umbral_pitch"),
            ("caida",    "umbral_caida"),
            ("malestar", "umbral_malestar"),
        ]:
            datos = np.array(self.buffer[clave])
            nuevo = float(np.mean(datos) + k * np.std(datos))
            setattr(self.cfg, attr, max(nuevo, getattr(self.cfg, attr) * 0.5))
        self.baseline_color.fijar()
        self.calibrado = True
        print(f"Calibración OK — "
              f"boca={self.cfg.umbral_boca:.3f} | "
              f"roll={self.cfg.umbral_roll:.1f}° | "
              f"pitch={self.cfg.umbral_pitch:.1f}° | "
              f"caida={self.cfg.umbral_caida:.3f} | "
              f"malestar={self.cfg.umbral_malestar:.3f}")

# ==============================================================
# MODELOS MEDIAPIPE
# ==============================================================

class ModelosMP:
    def __init__(self, cfg):
        face_opts = vision.FaceLandmarkerOptions(
            base_options=python.BaseOptions(model_asset_path="face_landmarker.task"),
            running_mode=vision.RunningMode.VIDEO,
            num_faces=cfg.num_faces,
            output_face_blendshapes=True,
            min_face_detection_confidence=cfg.min_confianza,
            min_face_presence_confidence=cfg.min_confianza,
            min_tracking_confidence=cfg.min_confianza,
        )
        pose_opts = vision.PoseLandmarkerOptions(
            base_options=python.BaseOptions(model_asset_path="pose_landmarker.task"),
            running_mode=vision.RunningMode.VIDEO,
            min_pose_detection_confidence=cfg.min_confianza,
            min_pose_presence_confidence=cfg.min_confianza,
            min_tracking_confidence=cfg.min_confianza,
        )
        self.face = vision.FaceLandmarker.create_from_options(face_opts)
        self.pose = vision.PoseLandmarker.create_from_options(pose_opts)

    def cerrar(self):
        try: self.face.close()
        except: pass
        try: self.pose.close()
        except: pass

# ==============================================================
# MÉTRICAS
# ==============================================================

def dist(a, b):
    return np.sqrt((a.x - b.x)**2 + (a.y - b.y)**2)

def blink_score(fr):
    try:
        bl = {b.category_name: b.score for b in fr.face_blendshapes[0]}
        return (bl.get("eyeBlinkLeft", 0) + bl.get("eyeBlinkRight", 0)) / 2
    except:
        return 0.0

def apertura_boca(lm):
    return dist(lm[BOCA_SUP], lm[BOCA_INF]) / (dist(lm[BOCA_IZQ], lm[BOCA_DER]) + 1e-6)

def angulos_cabeza(lm):
    f, m, n = lm[FRENTE], lm[MENTON], lm[NARIZ_TIP]
    roll  = abs(np.degrees(np.arctan2(m.x - f.x, m.y - f.y + 1e-6)))
    eje_y = (f.y + m.y) / 2
    pitch = abs((n.y - eje_y) / (abs(m.y - f.y) + 1e-6)) * 90
    return roll, pitch

def detectar_caida(pr):
    try:
        lm    = pr.pose_landmarks[0]
        nariz = lm[POSE_NARIZ]
        y_h   = (lm[POSE_HOMBRO_IZQ].y + lm[POSE_HOMBRO_DER].y) / 2
        frontal   = max(0.0, nariz.y - y_h)
        asimetria = abs(lm[POSE_HOMBRO_IZQ].y - lm[POSE_HOMBRO_DER].y)
        return max(frontal, asimetria * 0.6)
    except:
        return 0.0

def detectar_malestar(fr):
    if not fr.face_blendshapes:
        return 0.0
    bl = {b.category_name: b.score for b in fr.face_blendshapes[0]}
    score = sum(
        bl.get(nombre, 0.0) * peso
        for nombre, peso in BLENDSHAPES_MALESTAR.items()
    )
    return float(np.clip(score / _PESO_TOTAL_MALESTAR, 0.0, 1.0))

# ==============================================================
# DETECTOR PRINCIPAL
# ==============================================================

@dataclass
class Estado:
    blink:          float = 0
    boca:           float = 0
    roll:           float = 0
    pitch:          float = 0
    caida:          float = 0
    palidez:        float = 0
    malestar:       float = 0
    ear:            float = 0
    mov_iris:       float = 0
    bostezo_activo: bool  = False  # ← NUEVO v7b
    total_bostezos: int   = 0      # ← NUEVO v7b
    nivel:          int   = 0
    alertas:        list  = field(default_factory=list)
    fps:            float = 0

class DetectorLipotimia:
    def __init__(self, cfg):
        self.cfg = cfg
        self.f = {k: EMA(cfg.alpha_ema)
                  for k in ["blink","boca","roll","pitch","caida","palidez","malestar"]}
        self.frames_ojos = 0
        self.hist = deque(maxlen=cfg.ventana_riesgo)

    def filtrar(self, blink, boca, roll, pitch, caida, palidez, malestar):
        return (
            self.f["blink"].update(blink),
            self.f["boca"].update(boca),
            self.f["roll"].update(roll),
            self.f["pitch"].update(pitch),
            self.f["caida"].update(caida),
            self.f["palidez"].update(palidez),
            self.f["malestar"].update(malestar),
        )

    def evaluar(self, blink, boca, palidez, malestar, alerta_mirada,
                roll_ok, pitch_ok, caida_ok, movimiento_rapido):
        """
        v8: recibe flags ya filtrados por FiltroMovimientoVoluntario.

        Estrategia 1 (velocidad): roll_ok/pitch_ok/caida_ok son False
          si el movimiento fue demasiado rápido (voluntario).

        Estrategia 2 (coherencia): antes de sumar puntos al nivel,
          comprueba que haya al menos min_params_coherencia señales
          distintas activas. Una sola señal aislada no sube de nivel.

        Estrategia 3 (duración): roll_ok/pitch_ok/caida_ok solo son
          True si llevan frames_postural_minimo frames consecutivos.
        """
        c = self.cfg
        alertas = []
        # Mapa señal → puntos (solo se añaden si la señal está activa)
        senales = []

        self.frames_ojos = self.frames_ojos + 1 if blink > c.umbral_blink \
                           else max(0, self.frames_ojos - 1)
        if self.frames_ojos > c.frames_ojos_umbral:
            senales.append(("OJOS CERRADOS", 3))
        if boca     > c.umbral_boca:     senales.append(("BOCA ABIERTA",   1))
        if palidez  > c.umbral_palidez:  senales.append(("PALIDEZ",        2))
        if malestar > c.umbral_malestar: senales.append(("MALESTAR",       1))
        if alerta_mirada:                senales.append(("MIRADA FIJA",    3))

        # Parámetros posturales: solo si pasan filtros velocidad+duración
        if roll_ok:  senales.append(("CABEZA LATERAL", 2))
        if pitch_ok: senales.append(("CABEZA CAIDA",   2))
        if caida_ok: senales.append(("CAIDA POSTURAL", 3))

        # ── Estrategia 2: coherencia ─────────────────────────────
        # Si hay señales pero menos de min_params_coherencia, no subimos
        # de nivel — puede ser un giro al hablar con alguien
        if len(senales) >= c.min_params_coherencia:
            puntos = sum(p for _, p in senales)
            alertas = [n for n, _ in senales]
        elif len(senales) > 0:
            # Señal aislada: la anotamos pero con 0 puntos de nivel
            puntos = 0
            alertas = [n + "*" for n, _ in senales]  # asterisco = aislada
        else:
            puntos = 0

        self.hist.append(0 if puntos == 0 else 1 if puntos <= 2 else 2)
        return int(round(np.mean(self.hist))), alertas

# ==============================================================
# LOGGER
# ==============================================================

class Logger:
    """
    v7c: acumula TODOS los eventos de la sesión en memoria y al cerrar
    genera dos archivos:
      · /content/historico_sesion.csv  — frame a frame completo
      · /content/informe_sesion.pdf    — resumen narrativo con línea
                                         de tiempo de estados y alertas
    """

    NOMBRES_NIVEL = {0: "NORMAL", 1: "PRECAUCION", 2: "ALERTA"}
    COLORES_NIVEL = {
        "NORMAL":     colors.HexColor("#1a7a3a"),
        "PRECAUCION": colors.HexColor("#0077aa"),
        "ALERTA":     colors.HexColor("#cc2200"),
    }

    def __init__(self):
        self._registros: list = []        # lista de dicts, uno por frame
        self._eventos:   list = []        # cambios de estado (para línea de tiempo)
        self._nivel_prev = -1
        self._t_inicio   = time.strftime("%H:%M:%S")
        self._fecha      = time.strftime("%d/%m/%Y")

    def escribir(self, e):
        ts = time.strftime("%H:%M:%S")
        self._registros.append({
            "ts":            ts,
            "blink":         round(e.blink,    3),
            "boca":          round(e.boca,     3),
            "roll":          round(e.roll,     1),
            "pitch":         round(e.pitch,    1),
            "caida":         round(e.caida,    3),
            "palidez":       round(e.palidez,  3),
            "malestar":      round(e.malestar, 3),
            "ear":           round(e.ear,      3),
            "mov_iris":      round(e.mov_iris, 4),
            "nivel":         e.nivel,
            "nivel_txt":     self.NOMBRES_NIVEL[e.nivel],
            "alertas":       ";".join(e.alertas),
            "bostezo":       1 if e.bostezo_activo else 0,
            "total_bostezos": e.total_bostezos,
            "fps":           round(e.fps, 1),
        })
        # Detectar cambio de estado para línea de tiempo
        if e.nivel != self._nivel_prev:
            self._eventos.append({
                "ts":    ts,
                "nivel": self.NOMBRES_NIVEL[e.nivel],
                "alertas": ";".join(e.alertas) or "—",
            })
            self._nivel_prev = e.nivel

    def guardar_csv(self, ruta="/content/historico_sesion.csv"):
        if not self._registros:
            print("⚠ Sin datos para CSV.")
            return
        campos = list(self._registros[0].keys())
        with open(ruta, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=campos)
            w.writeheader()
            w.writerows(self._registros)
        print(f"✔ CSV guardado → {ruta}  ({len(self._registros)} frames)")

    def guardar_pdf(self, ruta="/content/informe_sesion.pdf",
                    total_bostezos=0, ultimo_bostezo="—"):
        if not self._registros:
            print("⚠ Sin datos para PDF.")
            return

        doc = SimpleDocTemplate(ruta, pagesize=A4,
                                 leftMargin=2*cm, rightMargin=2*cm,
                                 topMargin=2*cm, bottomMargin=2*cm)
        estilos = getSampleStyleSheet()
        e_titulo  = ParagraphStyle("titulo",  parent=estilos["Title"],
                                    fontSize=18, spaceAfter=4, textColor=colors.HexColor("#1a1a2e"))
        e_subtit  = ParagraphStyle("subtit",  parent=estilos["Normal"],
                                    fontSize=10, textColor=colors.grey, spaceAfter=12)
        e_seccion = ParagraphStyle("seccion", parent=estilos["Heading2"],
                                    fontSize=12, spaceBefore=14, spaceAfter=6,
                                    textColor=colors.HexColor("#1a1a2e"))
        e_normal  = ParagraphStyle("normal",  parent=estilos["Normal"], fontSize=9, leading=13)
        e_evento  = ParagraphStyle("evento",  parent=estilos["Normal"], fontSize=8,
                                    leading=12, leftIndent=8)

        t_fin     = self._registros[-1]["ts"]
        n_frames  = len(self._registros)
        dur_seg   = n_frames / max(self._registros[-1]["fps"] if self._registros else 12, 1)

        # Estadísticas globales
        niveles   = [r["nivel"] for r in self._registros]
        n_normal  = niveles.count(0)
        n_precau  = niveles.count(1)
        n_alerta  = niveles.count(2)

        from collections import Counter
        todas_alertas = [a for r in self._registros
                         for a in r["alertas"].split(";") if a and a != "—"]
        top_alertas   = Counter(todas_alertas).most_common(5)

        def med(campo):
            vals = [r[campo] for r in self._registros]
            return round(sum(vals)/len(vals), 3) if vals else 0

        story = []

        # — Cabecera —
        story.append(Paragraph("Informe de sesión — Detector de Lipotimia", e_titulo))
        story.append(Paragraph(
            f"Fecha: {self._fecha} &nbsp;·&nbsp; Inicio: {self._t_inicio} &nbsp;·&nbsp; "
            f"Fin: {t_fin} &nbsp;·&nbsp; Frames analizados: {n_frames}", e_subtit))
        story.append(HRFlowable(width="100%", thickness=1,
                                 color=colors.HexColor("#cccccc"), spaceAfter=10))

        # — Resumen de estados —
        story.append(Paragraph("Resumen de estados", e_seccion))
        datos_estados = [
            ["Estado", "Frames", "% del tiempo"],
            ["NORMAL",     str(n_normal), f"{100*n_normal/n_frames:.1f}%"],
            ["PRECAUCIÓN", str(n_precau), f"{100*n_precau/n_frames:.1f}%"],
            ["ALERTA",     str(n_alerta), f"{100*n_alerta/n_frames:.1f}%"],
        ]
        t_estados = Table(datos_estados, colWidths=[5*cm, 4*cm, 4*cm])
        t_estados.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR",    (0,0), (-1,0), colors.white),
            ("FONTSIZE",     (0,0), (-1,-1), 9),
            ("ALIGN",        (0,0), (-1,-1), "CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#f5f5f5"), colors.white]),
            ("GRID",         (0,0), (-1,-1), 0.3, colors.HexColor("#cccccc")),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            # Color por fila de estado
            ("TEXTCOLOR", (0,1), (-1,1), colors.HexColor("#1a7a3a")),
            ("TEXTCOLOR", (0,2), (-1,2), colors.HexColor("#0077aa")),
            ("TEXTCOLOR", (0,3), (-1,3), colors.HexColor("#cc2200")),
            ("FONTNAME",  (0,1), (-1,-1), "Helvetica-Bold"),
        ]))
        story.append(t_estados)
        story.append(Spacer(1, 10))

        # — Alertas más frecuentes —
        story.append(Paragraph("Alertas más frecuentes", e_seccion))
        if top_alertas:
            datos_alertas = [["Alerta", "Veces"]] + \
                            [[a, str(c)] for a, c in top_alertas]
            t_alertas = Table(datos_alertas, colWidths=[9*cm, 4*cm])
            t_alertas.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,0), colors.HexColor("#1a1a2e")),
                ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                ("FONTSIZE",      (0,0), (-1,-1), 9),
                ("ALIGN",         (1,0), (1,-1), "CENTER"),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#f5f5f5"), colors.white]),
                ("GRID",          (0,0), (-1,-1), 0.3, colors.HexColor("#cccccc")),
                ("TOPPADDING",    (0,0), (-1,-1), 5),
                ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ]))
            story.append(t_alertas)
        else:
            story.append(Paragraph("Ninguna alerta registrada.", e_normal))
        story.append(Spacer(1, 10))

        # — Bostezos —
        story.append(Paragraph("Bostezos", e_seccion))
        story.append(Paragraph(
            f"Total detectados: <b>{total_bostezos}</b> &nbsp;·&nbsp; "
            f"Último: <b>{ultimo_bostezo}</b>", e_normal))
        story.append(Spacer(1, 10))

        # — Métricas medias —
        story.append(Paragraph("Métricas medias de la sesión", e_seccion))
        datos_met = [
            ["Métrica", "Media sesión"],
            ["Blink score",      str(med("blink"))],
            ["Apertura boca",    str(med("boca"))],
            ["Roll cabeza (°)",  str(med("roll"))],
            ["Pitch cabeza (°)", str(med("pitch"))],
            ["Caída postural",   str(med("caida"))],
            ["Palidez",          str(med("palidez"))],
            ["Malestar",         str(med("malestar"))],
            ["EAR",              str(med("ear"))],
        ]
        t_met = Table(datos_met, colWidths=[7*cm, 6*cm])
        t_met.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
            ("FONTSIZE",      (0,0), (-1,-1), 9),
            ("ALIGN",         (1,0), (1,-1), "CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#f5f5f5"), colors.white]),
            ("GRID",          (0,0), (-1,-1), 0.3, colors.HexColor("#cccccc")),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ]))
        story.append(t_met)
        story.append(Spacer(1, 10))

        # — Línea de tiempo de cambios de estado —
        story.append(Paragraph("Línea de tiempo — cambios de estado", e_seccion))
        if self._eventos:
            for ev in self._eventos:
                color_txt = self.COLORES_NIVEL.get(ev["nivel"], colors.black)
                story.append(Paragraph(
                    f'<font color="{color_txt.hexval() if hasattr(color_txt,"hexval") else "#333"}">'
                    f'<b>{ev["ts"]}</b></font> &nbsp;→&nbsp; '
                    f'<b>{ev["nivel"]}</b> &nbsp; <font size="8">{ev["alertas"]}</font>',
                    e_evento))
        else:
            story.append(Paragraph("Sin cambios de estado registrados.", e_normal))

        story.append(Spacer(1, 14))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Spacer(1, 4))
        story.append(Paragraph(
            f"Generado automáticamente por Detector de Lipotimia v7c · {self._fecha}",
            ParagraphStyle("pie", parent=estilos["Normal"],
                           fontSize=7, textColor=colors.grey, alignment=TA_CENTER)))

        doc.build(story)
        print(f"✔ PDF guardado → {ruta}")

    def cerrar(self):
        pass   # archivos gestionados por guardar_csv / guardar_pdf


# ==============================================================
# WEBCAM
# ==============================================================

def iniciar_camara(timeout=40):
    """
    Ejecutar SOLO desde el hilo principal (Celda 1).
    Lanza el popup de permiso y espera hasta que la cámara esté lista.
    eval_js solo funciona en el hilo principal de Colab.
    """
    display(Javascript('''
    async function initCamera() {
        if (window._webcamVideo) return;
        window._webcamError = null;
        try {
            const s = await navigator.mediaDevices.getUserMedia(
                {video:{width:640,height:480,facingMode:"user"}}
            );
            const v = document.createElement('video');
            v.style.display = 'none';
            document.body.appendChild(v);
            v.srcObject = s;
            await v.play();
            window._webcamVideo = v;
        } catch(e) { window._webcamError = e.message; }
    }
    initCamera();
    '''))
    print("Acepta el permiso de cámara en el navegador…")
    inicio = time.time()
    while time.time() - inicio < timeout:
        time.sleep(1)
        try:
            ok  = eval_js('window._webcamVideo != null && window._webcamVideo.readyState >= 2')
            err = eval_js('window._webcamError || ""')
        except Exception:
            continue
        if ok:
            print("✔ Cámara lista — ejecuta la Celda 2 para ver los botones")
            return True
        if err:
            print(f"✘ Error: {err}")
            return False
    print("✘ Timeout — ¿aceptaste el permiso?")
    return False

def capturar_frame():
    try:
        data = eval_js('''
        (function(){
            const v = window._webcamVideo;
            if (!v || v.readyState < 2) return null;
            const c = document.createElement('canvas');
            c.width  = v.videoWidth  || 640;
            c.height = v.videoHeight || 480;
            c.getContext('2d').drawImage(v, 0, 0);
            return c.toDataURL('image/jpeg', 0.8);
        })()
        ''')
        if not data: return None
        img = Image.open(io.BytesIO(base64.b64decode(data.split(',')[1])))
        return cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    except Exception as e:
        print("capture error:", e)
        return None


# ==============================================================
# RENDER
# ==============================================================

NIVELES = {
    0: ((0, 160, 0),   "NORMAL",     (255, 255, 255)),
    1: ((0, 190, 220), "PRECAUCION", (0, 0, 0)),
    2: ((0, 0, 210),   "ALERTA",     (255, 255, 255)),
}

def dibujar(frame, e, calibrado, frames_cal, total_cal):
    h, w = frame.shape[:2]
    cv2.rectangle(frame, (0, 0), (w, 50), (18, 18, 18), -1)
    cv2.putText(frame, "DETECTOR LIPOTIMIA v8", (15, 32),
                cv2.FONT_HERSHEY_SIMPLEX, 0.85, (255, 230, 0), 2)

    if not calibrado:
        p = int((frames_cal / max(total_cal, 1)) * (w - 20))
        cv2.rectangle(frame, (10, h-30), (w-10, h-12), (50, 50, 50), -1)
        cv2.rectangle(frame, (10, h-30), (10+p, h-12), (0, 200, 200), -1)
        cv2.putText(frame, f"Calibrando... {frames_cal}/{total_cal}",
                    (15, h-35), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 220, 220), 2)
        return

    x0 = w - 295
    cv2.rectangle(frame, (x0, 60), (w-10, 360), (28, 28, 28), -1)
    metricas = [
        f"Blink   : {e.blink:.2f}",
        f"Boca    : {e.boca:.2f}",
        f"Roll    : {e.roll:.1f}gr",
        f"Pitch   : {e.pitch:.1f}gr",
        f"Caida   : {e.caida:.3f}",
        f"Palidez : {e.palidez:.3f}",
        f"Malestar: {e.malestar:.3f}",
        f"EAR     : {e.ear:.3f}",
        f"Iris mov: {e.mov_iris:.4f}",
        f"Bostezos: {e.total_bostezos}",   # ← NUEVO v7b — contador acumulado
        f"FPS     : {e.fps:.1f}",
    ]
    for i, t in enumerate(metricas):
        cv2.putText(frame, t, (x0+12, 85+i*26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.50, (220, 220, 220), 1)

    # Indicador de bostezo en curso — aparece en esquina superior izquierda
    if e.bostezo_activo:
        cv2.rectangle(frame, (10, 58), (200, 88), (30, 30, 30), -1)
        cv2.putText(frame, "BOSTEZO", (16, 80),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.65, (0, 220, 255), 2)

    col, txt, ctxt = NIVELES[e.nivel]
    cv2.rectangle(frame, (0, h-70), (w, h), col, -1)
    cv2.putText(frame, txt, (20, h-28),
                cv2.FONT_HERSHEY_SIMPLEX, 1.1, ctxt, 3)
    if e.alertas:
        cv2.putText(frame, " | ".join(e.alertas), (230, h-28),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, ctxt, 2)

# ==============================================================
# ==============================================================
# CONTROL DE SESIÓN — v7f  (arquitectura definitiva)
# ==============================================================
# En Colab, eval_js NO funciona desde callbacks de widgets.
# Solución: el JS hace PUSH de frames al kernel mediante
# google.colab.kernel.invokeFunction() — funciona desde
# cualquier hilo y no requiere eval_js en absoluto.
#
# Flujo:
#   JS (navegador) captura frame → lo envía al kernel
#   Python (callback registrado) lo pone en _cola_frames
#   Hilo detector consume _cola_frames y procesa
#   Botón TERMINAR → pone None en la cola → hilo para
# ==============================================================

import queue      as _queue
import threading  as _threading
import base64     as _base64

_cola_frames   = _queue.Queue(maxsize=4)
_sesion_activa = False


def _registrar_captura_js():
    """
    Registra la función Python que el JS llama para enviar frames.
    Debe ejecutarse UNA VEZ desde el hilo principal antes de iniciar.
    """
    from google.colab import output as _colab_output

    def _recibir_frame(data_url):
        """Llamada por el JS con cada frame en base64."""
        if not _sesion_activa:
            return
        try:
            b64 = data_url.split(',')[1]
            img = Image.open(io.BytesIO(_base64.b64decode(b64)))
            frame = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
            try:
                _cola_frames.put_nowait(frame)
            except _queue.Full:
                pass   # detector ocupado, descartamos frame
        except Exception as e:
            pass

    _colab_output.register_callback('enviar_frame', _recibir_frame)


def _iniciar_captura_js(fps=12):
    """Arranca el bucle de captura en el navegador."""
    intervalo = int(1000 / fps)
    display(Javascript(f'''
    (function() {{
        if (window._captureTimer) clearInterval(window._captureTimer);
        const v = window._webcamVideo;
        if (!v) {{ console.warn("Cámara no disponible"); return; }}
        const c = document.createElement('canvas');
        c.width  = v.videoWidth  || 640;
        c.height = v.videoHeight || 480;
        const ctx = c.getContext('2d');
        window._captureTimer = setInterval(function() {{
            if (!window._sesionActiva) {{
                clearInterval(window._captureTimer);
                return;
            }}
            ctx.drawImage(v, 0, 0, c.width, c.height);
            const dataUrl = c.toDataURL('image/jpeg', 0.7);
            google.colab.kernel.invokeFunction('enviar_frame', [dataUrl], {{}});
        }}, {intervalo});
        console.log("Captura JS iniciada a {fps} fps");
    }})();
    '''))


def _detener_captura_js():
    """Para el bucle JS y señala parada."""
    display(Javascript('''
    window._sesionActiva = false;
    if (window._captureTimer) {
        clearInterval(window._captureTimer);
        window._captureTimer = null;
    }
    console.log("Captura JS detenida");
    '''))


def _bucle_detector(cfg, estado_lbl, salida, dh):
    """Corre en hilo secundario. Consume frames de _cola_frames."""
    global _sesion_activa

    baseline_color   = BaselineColor()
    modelos          = ModelosMP(cfg)
    detector         = DetectorLipotimia(cfg)
    detector_mirada  = DetectorMiradaFija(cfg, baseline_color)
    detector_bostezo = DetectorBostezo(cfg)
    filtro_mov       = FiltroMovimientoVoluntario(cfg)   # ← NUEVO v8
    calibrador       = Calibrador(cfg, baseline_color)
    logger           = Logger()
    t_prev           = time.time()

    with salida:
        print(f"🔴 Grabando — quédate quieto/a {cfg.frames_calibracion} frames…")

    try:
        while _sesion_activa:
            try:
                frame = _cola_frames.get(timeout=1.0)
            except _queue.Empty:
                continue

            if frame is None:
                break

            rgb    = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            mp_img = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
            ts     = int(time.time() * 1000)

            fr = modelos.face.detect_for_video(mp_img, ts)
            pr = modelos.pose.detect_for_video(mp_img, ts)

            blink = boca = roll = pitch = caida = palidez = malestar = 0.0
            ear = mov_iris = 0.0
            alerta_mirada = bostezo_activo = False
            lm = None

            if fr.face_landmarks:
                lm          = fr.face_landmarks[0]
                blink       = blink_score(fr)
                boca        = apertura_boca(lm)
                roll, pitch = angulos_cabeza(lm)
                malestar    = detectar_malestar(fr)
                palidez     = baseline_color.score_palidez(frame, lm)
                ear, mov_iris, alerta_mirada = detector_mirada.actualizar(lm)
                _, _, bostezo_activo = detector_bostezo.actualizar(lm, fr)

            if pr.pose_landmarks:
                caida = detectar_caida(pr)

            calibrador.agregar(frame, lm, blink, boca, roll, pitch,
                               caida, malestar, ear=ear)

            blink, boca, roll, pitch, caida, palidez, malestar = detector.filtrar(
                blink, boca, roll, pitch, caida, palidez, malestar
            )

            # v8: aplicar filtros de movimiento voluntario ANTES de evaluar
            roll_ok, pitch_ok, caida_ok, mov_rapido = filtro_mov.actualizar(
                roll, pitch, caida, cfg
            )

            nivel, alertas = detector.evaluar(
                blink, boca, palidez, malestar, alerta_mirada,
                roll_ok, pitch_ok, caida_ok, mov_rapido
            )

            now    = time.time()
            fps    = 1.0 / max(now - t_prev, 1e-6)
            t_prev = now

            e = Estado(blink, boca, roll, pitch, caida, palidez, malestar,
                       ear, mov_iris, bostezo_activo,
                       detector_bostezo.total_bostezos, nivel, alertas, fps)
            logger.escribir(e)

            dibujar(frame, e, calibrador.calibrado,
                    len(calibrador.buffer["blink"]), cfg.frames_calibracion)
            _, buf = cv2.imencode('.jpg', frame)
            dh.update(IPImage(data=buf.tobytes()))

    finally:
        modelos.cerrar()
        b = detector_bostezo.total_bostezos
        n = len(logger._registros)
        with salida:
            print(f"\n✔ Sesión terminada — {n} frames | {b} bostezos")
        logger.guardar_csv()
        logger.guardar_pdf(total_bostezos=b,
                           ultimo_bostezo=detector_bostezo.ultimo_bostezo)
        estado_lbl.value = "✔ Sesión finalizada — descarga el informe desde la carpeta de Colab"
        with salida:
            print("Panel de Archivos (barra lateral izquierda) → descarga.")


def lanzar_interfaz():
    import ipywidgets as widgets
    from IPython.display import display as ipy_display
    global _sesion_activa, _cola_frames

    CFG = Config(
        fps_objetivo=12.0,
        frames_calibracion=50,
        umbral_palidez=0.25,
        umbral_malestar=0.30,
        ear_margen_sigma=2.0,
        umbral_movimiento_iris=0.008,
        frames_mirada_fija=22,
        umbral_mar_bostezo=0.45,
        umbral_squint_bostezo=0.25,
        frames_bostezo=14,
            # v8: filtros de movimiento voluntario
            umbral_velocidad_giro=3.5,   # grados/frame; sube si hay muchos falsos positivos
            min_params_coherencia=2,     # mínimo 2 señales distintas para subir de nivel
            frames_postural_minimo=8,    # ~0.7s sostenido antes de que postura cuente
    )

    btn_iniciar  = widgets.Button(
        description="▶  INICIAR",
        button_style="success",
        layout=widgets.Layout(width="160px", height="44px"),
        style={"font_weight": "bold", "font_size": "14px"},
    )
    btn_terminar = widgets.Button(
        description="⏹  TERMINAR",
        button_style="danger",
        layout=widgets.Layout(width="160px", height="44px"),
        style={"font_weight": "bold", "font_size": "14px"},
        disabled=True,
    )
    estado_lbl = widgets.Label(value="Pulsa INICIAR para comenzar")
    salida     = widgets.Output()
    dh         = display(None, display_id=True)

    ipy_display(widgets.VBox([
        widgets.HTML("<h3 style='margin:0 0 8px 0'> Detector de Lipotimia v7f</h3>"),
        widgets.HBox([btn_iniciar, btn_terminar],
                     layout=widgets.Layout(gap="12px")),
        estado_lbl,
        salida,
    ]))

    def on_terminar(_):
        global _sesion_activa
        _sesion_activa   = False
        _detener_captura_js()
        try: _cola_frames.put_nowait(None)
        except: pass
        estado_lbl.value = "Finalizando sesión…"

    def on_iniciar(_):
        global _sesion_activa, _cola_frames
        if _sesion_activa:
            return

        # Limpiar cola
        while not _cola_frames.empty():
            try: _cola_frames.get_nowait()
            except: break

        btn_iniciar.disabled  = True
        btn_terminar.disabled = False
        estado_lbl.value      = "🔴 Grabando…"
        _sesion_activa        = True

        # Arrancar JS de captura en el navegador
        display(Javascript("window._sesionActiva = true;"))
        _iniciar_captura_js(fps=int(CFG.fps_objetivo))

        # Arrancar hilo detector
        hilo = _threading.Thread(
            target=_bucle_detector,
            args=(CFG, estado_lbl, salida, dh),
            daemon=True
        )
        hilo.start()

        def _esperar_fin():
            hilo.join()
            btn_iniciar.disabled  = False
            btn_terminar.disabled = True

        _threading.Thread(target=_esperar_fin, daemon=True).start()

    btn_iniciar.on_click(on_iniciar)
    btn_terminar.on_click(on_terminar)


# ==============================================================
# EJECUCIÓN - ejecutar 2 veces.
# ==============================================================
iniciar_camara()          # pide permiso — hilo principal
_registrar_captura_js()   # registra callback Python para el JS
lanzar_interfaz()         # muestra botones
